name = "Weeny Hut (neoforge-dev)"
author = "mpryor"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a23bd1379c96eb7f4e90502a8d59cfbe1e7b208a0b3e39b2a78ff2d8da9c9079"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
